name: Bug
description: Something isn't working
title: '[BUG] <title>'
labels: ['bug']
assignees:
  - hywax

body:
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of ya-metrika are you running?
      placeholder: 3.0.0 ← should look like this (check composer.json)
    validations:
      required: false

  - type: textarea
    id: reproduce
    attributes:
      label: Describe the problem
      description: Please describe exactly what is not working, include the steps to reproduce, actual result and expected result
      placeholder: When doing ABC then DEF, I expect to see XYZ, but I actually see ZYX
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Additional info
      description: Logs? Screenshots? Yes, please.
      placeholder: If the issue happens during build-time, include terminal logs.
    validations:
      required: false
